"use strict";
exports.__esModule = true;
var point_1 = require("./models/point");
var planet_1 = require("./models/planet");
var planet_utils_1 = require("./planet_utils");
var vector_1 = require("./models/vector");
var vector = new vector_1.Vector(0, new point_1.Point(0, 0), new point_1.Point(2, 2));
var planet1 = new planet_1.Planet("earth", 10 * Math.pow(6, 24), new point_1.Point(0, 0), vector);
var vector1 = new vector_1.Vector(0, new point_1.Point(1, 2), new point_1.Point(2, 2));
var planet2 = new planet_1.Planet("sun", 200 * Math.pow(1, 30), new point_1.Point(1, 3), vector1);
var planet3 = new planet_1.Planet("x", 2 * Math.pow(1, 22), new point_1.Point(2, 7), vector1);
var planet4 = new planet_1.Planet("a", 3 * Math.pow(1, 21), new point_1.Point(4, 2), vector1);
console.log("0. planet1", planet1.position);
console.log("0. planet2", planet2.position);
console.log("0. planet3", planet3.position);
console.log("0. planet4", planet4.position);
planet_utils_1.Planet_utils.updateAllPlanet([planet1, planet2, planet3, planet4], 1);
console.log("1. planet1", planet1.position);
console.log("1. planet2", planet2.position);
console.log("1. planet3", planet3.position);
console.log("1. planet4", planet4.position);
planet_utils_1.Planet_utils.updateAllPlanet([planet1, planet2, planet3, planet4], 2);
console.log("2. planet1", planet1.position);
console.log("2. planet2", planet2.position);
console.log("2. planet3", planet3.position);
console.log("2. planet4", planet4.position);
